[build]
jobs = 0
build-dir = "/var/ribosome/build"
cache-dir = "/var/ribosome/vacuole"

[compiler]
optimization = "speed"
arch = "x86-64-v3"
cflags = "-O2 -pipe -march=x86-64-v3 -mtune=generic -fstack-protector-strong"
ldflags = "-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"

[features]
global = ["lto", "strip"]

[features.per-package]
gcc = ["dlang", "go"]
linux-kernel = ["module-signing", "hardened"]

[sandbox]
type = "btrfs-subvolume"
network = true
max-memory = "8G"

[repository]
mirrors = [
    "https://repo.lysine-os.org/nucleus",
    "https://mirror.lysine-os.org/nucleus",
]

[snapshot]
auto-snapshot = true
keep-daily = 7
keep-weekly = 4
keep-monthly = 2
